[functions.admin-api]
verify_jwt = false
entrypoint = "./functions/admin-api/index.ts"

[functions.admin-login]
verify_jwt = false
entrypoint = "./functions/admin-login/index.ts"

[functions.tenant-signup]
verify_jwt = false
entrypoint = "./functions/tenant-signup/index.ts"

